spring:
  datasource:
    username: root
    password: ahdzr123
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/springboot1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

